#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # 停止服务
        systemctl stop qifeng-scmd.service || true
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument: $1" >&2
        exit 1
        ;;
esac

exit 0
