# Service A - 依赖Service C
# Copyright (C) 2026-2026 Qifeng Shunshi Co., Ltd. All rights reserved.

serviceName: test_service_b #必要字段、且必须唯一
version: 1.0.0
autoStart: false

execution: #必要字段且路径是相对软件包根目录、不能存在..等改变父目录的路径
  command: ./bin/test_service_b #必要字段
  workDir: ./bin
  dataDir: ./data
  args: ["18002"]

needInitDB: true
sqlDir: ./sql

   
healthCheck:
  type: http
  interval_sec: 5
  timeout_sec: 2
  http_url: http://127.0.0.1:18002/health
  expected_status: 200
  retries: 3

resources:
  ports: [8080, 9090]  #端口
  Mem: 500M            #资源上限约束
  requires:
    - serviceName: test_service_c
      version: "1.0.0"
